"""updated companies table

Revision ID: 1fda1a6eba1f
Revises: 5ba0cb29d73e
Create Date: 2026-06-04 18:22:12.961400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1fda1a6eba1f"
down_revision: Union[str, Sequence[str], None] = "5ba0cb29d73e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE jobs;")
    op.drop_constraint(op.f("jobs_company_id_fkey"), "jobs", type_="foreignkey")
    op.create_foreign_key(None, "jobs", "companies", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.create_foreign_key(
        op.f("jobs_company_id_fkey"), "jobs", "users", ["company_id"], ["id"]
    )
    # ### end Alembic commands ###
