"""upgraded user table.

Revision ID: 2cb66cbcbf37
Revises: 9dc5c0faef8a
Create Date: 2026-05-25 22:42:25.021707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2cb66cbcbf37"
down_revision: Union[str, Sequence[str], None] = "9dc5c0faef8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum("student", "teacher", "admin", name="user_role")
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("admin", "student", "company", name="user_role"),
            server_default="student",
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "school",
        existing_type=postgresql.ENUM(
            "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
            "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
            "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
            "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
            name="institute",
        ),
        nullable=True,
        existing_server_default=sa.text(
            "'INDIAN INSTITUTE OF TECHNOLOGY MADRAS'::institute"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "school",
        existing_type=postgresql.ENUM(
            "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
            "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
            "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
            "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
            name="institute",
        ),
        nullable=False,
        existing_server_default=sa.text(
            "'INDIAN INSTITUTE OF TECHNOLOGY MADRAS'::institute"
        ),
    )
    op.drop_column("users", "role")
    user_role_enum = sa.Enum(name="user_role")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
