"""creating tables first time.

Revision ID: 31c4a5830f09
Revises:
Create Date: 2026-05-24 20:52:57.426948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "31c4a5830f09"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column(
            "school",
            sa.Enum(
                "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
                "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
                "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
                "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
                "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
                name="institute",
            ),
            server_default="INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("on-site", "remote", "hybrid", name="job_mode"),
            server_default="on-site",
            nullable=False,
        ),
        sa.Column(
            "job_type",
            sa.Enum("full-time", "part-time", "contract", name="job_type"),
            server_default="full-time",
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
