"""updated models studentProfile, CompanyProfile and User to make it a one-to-one relationship

Revision ID: 53b3dd370415
Revises: 909c89b24eae
Create Date: 2026-06-05 17:55:53.223046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b3dd370415'
down_revision: Union[str, Sequence[str], None] = '909c89b24eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['user_id'])
    op.create_unique_constraint(None, 'students', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
