"""added company status in companies database.

Revision ID: 6378e3bbac35
Revises: adad31a9820f
Create Date: 2026-06-04 20:56:24.501770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6378e3bbac35"
down_revision: Union[str, Sequence[str], None] = "adad31a9820f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    company_status = sa.Enum("pending","approved","rejected", name="company_status")
    company_status.create(op.get_bind(),checkfirst=True)
    op.add_column(
        "companies",
        sa.Column(
            "status",
            sa.Enum("verified", "pending", "rejected", name="company_status"),
            server_default="pending",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "status")
    company_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
