"""made status field inside company profile non-nullable

Revision ID: 909c89b24eae
Revises: 6378e3bbac35
Create Date: 2026-06-05 13:52:27.472830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '909c89b24eae'
down_revision: Union[str, Sequence[str], None] = '6378e3bbac35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='company_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::company_status"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='company_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::company_status"))
    # ### end Alembic commands ###
