"""upgraded User table

Revision ID: 95c8d081d63f
Revises: 2cb66cbcbf37
Create Date: 2026-05-26 00:13:09.607372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95c8d081d63f"
down_revision: Union[str, Sequence[str], None] = "2cb66cbcbf37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "school",
        existing_type=postgresql.ENUM(
            "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
            "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
            "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
            "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
            name="institute",
        ),
        type_=sa.Enum(
            "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
            "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
            "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
            "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
            name="institute",
        ),
        existing_nullable=True,
        existing_server_default=sa.text(
            "'INDIAN INSTITUTE OF TECHNOLOGY MADRAS'::institute"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "school",
        existing_type=sa.Enum(
            "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
            "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
            "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
            "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
            name="institute",
        ),
        type_=postgresql.ENUM(
            "INDIAN INSTITUTE OF TECHNOLOGY MADRAS",
            "INDIAN INSTITUTE OF TECHNOLOGY ROPAR",
            "INDIAN INSTITUTE OF TECHNOLOGY MANDI",
            "INDIAN INSTITUTE OF TECHNOLOGY BOMBAY",
            "INDIAN INSTITUTE OF TECHNOLOGY DELHI",
            name="institute",
        ),
        existing_nullable=True,
        existing_server_default=sa.text(
            "'INDIAN INSTITUTE OF TECHNOLOGY MADRAS'::institute"
        ),
    )
    # ### end Alembic commands ###
