"""updated job table.

Revision ID: 9dc5c0faef8a
Revises: 31c4a5830f09
Create Date: 2026-05-25 18:30:46.770138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9dc5c0faef8a"
down_revision: Union[str, Sequence[str], None] = "31c4a5830f09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "mode",
        existing_type=postgresql.ENUM("on-site", "remote", "hybrid", name="job_mode"),
        type_=sa.Enum("on-site", "remote", "hybrid", name="job_mode"),
        existing_nullable=False,
        existing_server_default=sa.text("'on-site'::job_mode"),
    )
    op.alter_column(
        "jobs",
        "job_type",
        existing_type=postgresql.ENUM(
            "full-time", "part-time", "contract", name="job_type"
        ),
        type_=sa.Enum("full-time", "part-time", "contract", name="job_type"),
        existing_nullable=False,
        existing_server_default=sa.text("'full-time'::job_type"),
    )
    op.alter_column("jobs", "description", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("jobs", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "jobs",
        "job_type",
        existing_type=sa.Enum("full-time", "part-time", "contract", name="job_type"),
        type_=postgresql.ENUM("full-time", "part-time", "contract", name="job_type"),
        existing_nullable=False,
        existing_server_default=sa.text("'full-time'::job_type"),
    )
    op.alter_column(
        "jobs",
        "mode",
        existing_type=sa.Enum("on-site", "remote", "hybrid", name="job_mode"),
        type_=postgresql.ENUM("on-site", "remote", "hybrid", name="job_mode"),
        existing_nullable=False,
        existing_server_default=sa.text("'on-site'::job_mode"),
    )
    # ### end Alembic commands ###
