"""added ondelete cascade

Revision ID: adad31a9820f
Revises: c2a98af05461
Create Date: 2026-06-04 19:21:25.873360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adad31a9820f'
down_revision: Union[str, Sequence[str], None] = 'c2a98af05461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('about', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'about')
    # ### end Alembic commands ###
