"""updated users table

Revision ID: bb6b0a0cdc27
Revises: 95c8d081d63f
Create Date: 2026-05-29 18:11:56.502417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6b0a0cdc27'
down_revision: Union[str, Sequence[str], None] = '95c8d081d63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'school')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school', postgresql.ENUM('INDIAN INSTITUTE OF TECHNOLOGY MADRAS', 'INDIAN INSTITUTE OF TECHNOLOGY ROPAR', 'INDIAN INSTITUTE OF TECHNOLOGY MANDI', 'INDIAN INSTITUTE OF TECHNOLOGY BOMBAY', 'INDIAN INSTITUTE OF TECHNOLOGY DELHI', name='institute'), server_default=sa.text("'INDIAN INSTITUTE OF TECHNOLOGY MADRAS'::institute"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
